OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/APPLICATIONS.csv'
BADFILE 'APPLICATIONS.bad'
DISCARDFILE 'APPLICATIONS.dsc'
INTO TABLE APPLICATIONS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    APPLICATION_ID,
    APP_DATE DATE "YYYY-MM-DD",
    DEC_DATE DATE "YYYY-MM-DD",
    DECISION,
    BANKER,
    CLIENT_NO,
    CLIENT_SHORT,
    REJECT_REASON,
    COMMITTEE,
    SALES,
    COGS,
    OPINCOME,
    GROSSMARGIN,
    TOTALOPERATIONALEXPENSES,
    SALARY,
    TRANSPORTATION,
    LEASE,
    TAXES,
    COMMUNAL,
    ADVERTISINGMARKETING,
    AMORTIZATION,
    LOANPERCENT,
    OTHEREXPENSES,
    NETINCOMEBS,
    OTHERINCOME,
    DIVIDEND,
    NETINCOME,
    DEBTSERVICE,
    PREVIOUSLOANFEE,
    FOUNDERSALARY,
    RECRUITSALARY,
    OTHERSALARY,
    OTHERLEASING,
    MONEYTRANSFER,
    EBITDA,
    EBIT,
    EBITDAMARGIN,
    GROSSINCOMEMARGIN,
    RETAINEDEARNINGS,
    NETINCOMEMARGIN,
    INCOMEBEFORETAX,
    REALNETINCOME,
    INCOMETAX
)
