-- ============================================================
-- Bank of Claude (BOC) - 10,000 loans/month population
-- CREATE TABLE DDL, run this FIRST in your personal schema.
-- Then load data with SQL*Loader using the .ctl files in ../sqlldr/
-- (see README.md for exact commands and load order).
-- ============================================================

-- ---------- DIM_CALENDAR ----------
CREATE TABLE DIM_CALENDAR (
    HIST_DATE       DATE PRIMARY KEY,
    YEAR_NO         NUMBER(4),
    QUARTER_NO      NUMBER(1),
    MONTH_NO        NUMBER(2),
    MONTH_NAME      VARCHAR2(20),
    FISCAL_PERIOD   VARCHAR2(10)
);

-- ---------- DIM_FX_RATE ----------
CREATE TABLE DIM_FX_RATE (
    CCY             VARCHAR2(3),
    HIST_DATE       DATE,
    RATE_TO_GEL     NUMBER(12,4),
    CONSTRAINT PK_DIM_FX_RATE PRIMARY KEY (CCY, HIST_DATE),
    CONSTRAINT FK_FX_CAL FOREIGN KEY (HIST_DATE) REFERENCES DIM_CALENDAR(HIST_DATE)
);

-- ---------- APPLICATIONS ----------
CREATE TABLE APPLICATIONS (
    APPLICATION_ID  NUMBER(9) PRIMARY KEY,
    APP_DATE        DATE,
    DEC_DATE        DATE,
    DECISION        VARCHAR2(2),
    BANKER          VARCHAR2(30),
    CLIENT_NO       NUMBER(9),
    CLIENT_SHORT    VARCHAR2(100),
    REJECT_REASON   VARCHAR2(100),
    COMMITTEE       NUMBER(1),
    SALES NUMBER(18,2), COGS NUMBER(18,2), OPINCOME NUMBER(18,2), GROSSMARGIN NUMBER(8,4),
    TOTALOPERATIONALEXPENSES NUMBER(18,2), SALARY NUMBER(18,2), TRANSPORTATION NUMBER(18,2),
    LEASE NUMBER(18,2), TAXES NUMBER(18,2), COMMUNAL NUMBER(18,2), ADVERTISINGMARKETING NUMBER(18,2),
    AMORTIZATION NUMBER(18,2), LOANPERCENT NUMBER(8,4), OTHEREXPENSES NUMBER(18,2),
    NETINCOMEBS NUMBER(18,2), OTHERINCOME NUMBER(18,2), DIVIDEND NUMBER(18,2), NETINCOME NUMBER(18,2),
    DEBTSERVICE NUMBER(18,2), PREVIOUSLOANFEE NUMBER(18,2), FOUNDERSALARY NUMBER(18,2),
    RECRUITSALARY NUMBER(18,2), OTHERSALARY NUMBER(18,2), OTHERLEASING NUMBER(18,2),
    MONEYTRANSFER NUMBER(18,2), EBITDA NUMBER(18,2), EBIT NUMBER(18,2), EBITDAMARGIN NUMBER(8,4),
    GROSSINCOMEMARGIN NUMBER(8,4), RETAINEDEARNINGS NUMBER(18,2), NETINCOMEMARGIN NUMBER(8,4),
    INCOMEBEFORETAX NUMBER(18,2), REALNETINCOME NUMBER(18,2), INCOMETAX NUMBER(18,2)
);

-- ---------- DIM_DEAL ----------
CREATE TABLE DIM_DEAL (
    DEAL_NO             NUMBER(9) PRIMARY KEY,
    CLIENT_NO           NUMBER(9),
    APPLICATION_ID      NUMBER(9),
    ORIGINATION_DATE    DATE,
    LOAN_SEGMENT        VARCHAR2(5),
    LOAN_PRODUCT        VARCHAR2(30),
    APPROVED_AMOUNT_GEL NUMBER(18,2),
    CLOSURE_REASON      VARCHAR2(20),
    CLOSURE_DATE        DATE,
    CONSTRAINT FK_DEAL_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID)
);

-- ---------- PORTFOLIO ----------
CREATE TABLE PORTFOLIO (
    HIST_DATE               DATE,
    LOAN_SEGMENT            VARCHAR2(5),
    CLIENT_NO               NUMBER(9),
    CLIENT_SHORT            VARCHAR2(100),
    CLIENT_GROUP            VARCHAR2(20),
    DEAL_NO                 NUMBER(9),
    LOAN_PRODUCT            VARCHAR2(30),
    START_DATE              DATE,
    MATURITY_DATE           DATE,
    EFFECTIVE_RATE          NUMBER(6,2),
    CCY                     VARCHAR2(3),
    REMAINING_PRINCIPAL     NUMBER(18,2),
    IFRS9_STAGE             NUMBER(1),
    OVERDUE_DATE            DATE,
    ALLOWANCE_GEL           NUMBER(18,2),
    PD                      NUMBER(8,4),
    LGD                     NUMBER(8,4),
    SECTOR                  VARCHAR2(40),
    REGION_BUSINESS         VARCHAR2(40),
    PROFIT_CENTER_CITY      VARCHAR2(30),
    CIG_GRADE               VARCHAR2(2),
    LTV                     NUMBER(8,4),
    BANKER                  VARCHAR2(30),
    RISK_MANAGER            VARCHAR2(30),
    REGIONAL_MANAGER        VARCHAR2(30),
    PROBLEM_PHASE           VARCHAR2(10),
    APPROVED_AMOUNT_GEL     NUMBER(18,2),
    DISBURSED_AMOUNT_GEL    NUMBER(18,2),
    REAL_ESTATE_COLLATERAL  NUMBER(18,2),
    AUTOMOBILE              NUMBER(18,2),
    GUARANTEE_COLLATERAL    NUMBER(18,2),
    OTHER_COLLATERAL        NUMBER(18,2),
    TOTAL_COLLATERAL        NUMBER(18,2),
    NEXT_PMT                NUMBER(18,2),
    APPLICATION_ID          NUMBER(9),
    PD_RISK_GROUP           NUMBER(1),
    PURPOSE                 VARCHAR2(30),
    CLIENT_ADDRESS_CITY     VARCHAR2(30),
    CONSTRAINT PK_PORTFOLIO PRIMARY KEY (HIST_DATE, DEAL_NO),
    CONSTRAINT FK_PORT_CAL FOREIGN KEY (HIST_DATE) REFERENCES DIM_CALENDAR(HIST_DATE),
    CONSTRAINT FK_PORT_DEAL FOREIGN KEY (DEAL_NO) REFERENCES DIM_DEAL(DEAL_NO),
    CONSTRAINT FK_PORT_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID)
);

-- ---------- RESTRUCTURINGS ----------
CREATE TABLE RESTRUCTURINGS (
    HIST_DATE   DATE,
    DEAL_NO     NUMBER(9),
    REST_TYPE   VARCHAR2(4),
    CONSTRAINT FK_REST_DEAL FOREIGN KEY (DEAL_NO) REFERENCES DIM_DEAL(DEAL_NO),
    CONSTRAINT FK_REST_CAL FOREIGN KEY (HIST_DATE) REFERENCES DIM_CALENDAR(HIST_DATE)
);

-- ---------- WRITE_OFF ----------
CREATE TABLE WRITE_OFF (
    HIST_DATE                   DATE,
    DEAL_NO                     NUMBER(9) PRIMARY KEY,
    WRITE_OFF_DATE               DATE,
    OVERDUE_DATE                DATE,
    CLIENT_NO                   NUMBER(9),
    CLIENT_SHORT                VARCHAR2(100),
    CLIENT_GROUP                VARCHAR2(20),
    LOAN_SEGMENT                VARCHAR2(5),
    LOAN_PRODUCT                VARCHAR2(30),
    SECTOR                      VARCHAR2(40),
    REGION_BUSINESS             VARCHAR2(40),
    BANKER                      VARCHAR2(30),
    RISK_MANAGER                VARCHAR2(30),
    REGIONAL_MANAGER            VARCHAR2(30),
    WRITE_OFF_AMOUNT_GEL         NUMBER(18,2),
    ALLOWANCE_AT_WRITE_OFF_GEL   NUMBER(18,2),
    NET_WRITE_OFF_GEL            NUMBER(18,2),
    WRITE_OFF_REASON             VARCHAR2(30),
    CONSTRAINT FK_WO_DEAL FOREIGN KEY (DEAL_NO) REFERENCES DIM_DEAL(DEAL_NO),
    CONSTRAINT FK_WO_CAL FOREIGN KEY (HIST_DATE) REFERENCES DIM_CALENDAR(HIST_DATE)
);

-- ---------- WRO_RECOVERIES ----------
CREATE TABLE WRO_RECOVERIES (
    HIST_DATE             DATE,
    DEAL_NO               NUMBER(9) PRIMARY KEY,
    RECOVERY_AMOUNT_GEL   NUMBER(18,2),
    CONSTRAINT FK_WRO_WO FOREIGN KEY (DEAL_NO) REFERENCES WRITE_OFF(DEAL_NO),
    CONSTRAINT FK_WRO_CAL FOREIGN KEY (HIST_DATE) REFERENCES DIM_CALENDAR(HIST_DATE)
);

-- ---------- REFINANCED ----------
CREATE TABLE REFINANCED (
    REFINANCE_DATE        DATE,
    DEAL_NO               NUMBER(9),
    REFINANCED_DEAL_NO    NUMBER(9),
    REFINANCE_AMOUNT      NUMBER(18,2),
    CONSTRAINT FK_REFI_NEW FOREIGN KEY (DEAL_NO) REFERENCES DIM_DEAL(DEAL_NO),
    CONSTRAINT FK_REFI_OLD FOREIGN KEY (REFINANCED_DEAL_NO) REFERENCES DIM_DEAL(DEAL_NO)
);

-- ---------- PURPOSE_DETAIL ----------
CREATE TABLE PURPOSE_DETAIL (
    DEAL_NO     NUMBER(9),
    PURPOSE     VARCHAR2(30),
    AMOUNT      NUMBER(18,2),
    CONSTRAINT FK_PD_DEAL FOREIGN KEY (DEAL_NO) REFERENCES DIM_DEAL(DEAL_NO)
);

-- ---------- SCHEDULED ----------
CREATE TABLE SCHEDULED (
    DEAL_NO             NUMBER(9),
    PAYMENT_DATE        DATE,
    PRINCIPAL_AMOUNT    NUMBER(18,2),
    INTEREST_AMOUNT     NUMBER(18,2),
    VALID_FROM          DATE,
    VALID_TO            DATE,
    CONSTRAINT PK_SCHEDULED PRIMARY KEY (DEAL_NO, PAYMENT_DATE, VALID_FROM),
    CONSTRAINT FK_SCHED_DEAL FOREIGN KEY (DEAL_NO) REFERENCES DIM_DEAL(DEAL_NO)
);

-- ---------- PAYMENT ----------
CREATE TABLE PAYMENT (
    PAYMENT_DATE        DATE,
    DEAL_NO             NUMBER(9),
    PRINCIPAL_AMOUNT    NUMBER(18,2),
    INTEREST_AMOUNT     NUMBER(18,2),
    CONSTRAINT FK_PMT_DEAL FOREIGN KEY (DEAL_NO) REFERENCES DIM_DEAL(DEAL_NO)
);

-- ---------- GAMBLERS ----------
CREATE TABLE GAMBLERS (
    CLIENT_NO       NUMBER(9),
    HIST_DATE       DATE,
    TRANSFER_IN     NUMBER(18,2),
    TRANSFER_OUT    NUMBER(18,2),
    CONSTRAINT FK_GAMB_CAL FOREIGN KEY (HIST_DATE) REFERENCES DIM_CALENDAR(HIST_DATE)
);

