OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/DIM_DEAL.csv'
BADFILE 'DIM_DEAL.bad'
DISCARDFILE 'DIM_DEAL.dsc'
INTO TABLE DIM_DEAL
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    DEAL_NO,
    CLIENT_NO,
    APPLICATION_ID,
    ORIGINATION_DATE DATE "YYYY-MM-DD",
    LOAN_SEGMENT,
    LOAN_PRODUCT,
    APPROVED_AMOUNT_GEL,
    CLOSURE_REASON,
    CLOSURE_DATE DATE "YYYY-MM-DD"
)
