OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/DIM_FX_RATE.csv'
BADFILE 'DIM_FX_RATE.bad'
DISCARDFILE 'DIM_FX_RATE.dsc'
INTO TABLE DIM_FX_RATE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    CCY,
    HIST_DATE DATE "YYYY-MM-DD",
    RATE_TO_GEL
)
