OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/DIM_CALENDAR.csv'
BADFILE 'DIM_CALENDAR.bad'
DISCARDFILE 'DIM_CALENDAR.dsc'
INTO TABLE DIM_CALENDAR
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    HIST_DATE DATE "YYYY-MM-DD",
    YEAR_NO,
    QUARTER_NO,
    MONTH_NO,
    MONTH_NAME,
    FISCAL_PERIOD
)
