OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/GAMBLERS.csv'
BADFILE 'GAMBLERS.bad'
DISCARDFILE 'GAMBLERS.dsc'
INTO TABLE GAMBLERS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    CLIENT_NO,
    HIST_DATE DATE "YYYY-MM-DD",
    TRANSFER_IN,
    TRANSFER_OUT
)
