OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/PAYMENT.csv'
BADFILE 'PAYMENT.bad'
DISCARDFILE 'PAYMENT.dsc'
INTO TABLE PAYMENT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    PAYMENT_DATE DATE "YYYY-MM-DD",
    DEAL_NO,
    PRINCIPAL_AMOUNT,
    INTEREST_AMOUNT
)
