OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/PORTFOLIO.csv'
BADFILE 'PORTFOLIO.bad'
DISCARDFILE 'PORTFOLIO.dsc'
INTO TABLE PORTFOLIO
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    HIST_DATE DATE "YYYY-MM-DD",
    LOAN_SEGMENT,
    CLIENT_NO,
    CLIENT_SHORT,
    CLIENT_GROUP,
    DEAL_NO,
    LOAN_PRODUCT,
    START_DATE DATE "YYYY-MM-DD",
    MATURITY_DATE DATE "YYYY-MM-DD",
    EFFECTIVE_RATE,
    CCY,
    REMAINING_PRINCIPAL,
    IFRS9_STAGE,
    OVERDUE_DATE DATE "YYYY-MM-DD",
    ALLOWANCE_GEL,
    PD,
    LGD,
    SECTOR,
    REGION_BUSINESS,
    PROFIT_CENTER_CITY,
    CIG_GRADE,
    LTV,
    BANKER,
    RISK_MANAGER,
    REGIONAL_MANAGER,
    PROBLEM_PHASE,
    APPROVED_AMOUNT_GEL,
    DISBURSED_AMOUNT_GEL,
    REAL_ESTATE_COLLATERAL,
    AUTOMOBILE,
    GUARANTEE_COLLATERAL,
    OTHER_COLLATERAL,
    TOTAL_COLLATERAL,
    NEXT_PMT,
    APPLICATION_ID,
    PD_RISK_GROUP,
    PURPOSE,
    CLIENT_ADDRESS_CITY
)
