OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/PURPOSE_DETAIL.csv'
BADFILE 'PURPOSE_DETAIL.bad'
DISCARDFILE 'PURPOSE_DETAIL.dsc'
INTO TABLE PURPOSE_DETAIL
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    DEAL_NO,
    PURPOSE,
    AMOUNT
)
