OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/REFINANCED.csv'
BADFILE 'REFINANCED.bad'
DISCARDFILE 'REFINANCED.dsc'
INTO TABLE REFINANCED
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    REFINANCE_DATE DATE "YYYY-MM-DD",
    DEAL_NO,
    REFINANCED_DEAL_NO,
    REFINANCE_AMOUNT
)
