OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/RESTRUCTURINGS.csv'
BADFILE 'RESTRUCTURINGS.bad'
DISCARDFILE 'RESTRUCTURINGS.dsc'
INTO TABLE RESTRUCTURINGS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    HIST_DATE DATE "YYYY-MM-DD",
    DEAL_NO,
    REST_TYPE
)
