OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/SCHEDULED.csv'
BADFILE 'SCHEDULED.bad'
DISCARDFILE 'SCHEDULED.dsc'
INTO TABLE SCHEDULED
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    DEAL_NO,
    PAYMENT_DATE DATE "YYYY-MM-DD",
    PRINCIPAL_AMOUNT,
    INTEREST_AMOUNT,
    VALID_FROM DATE "YYYY-MM-DD",
    VALID_TO DATE "YYYY-MM-DD"
)
