OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/WRITE_OFF.csv'
BADFILE 'WRITE_OFF.bad'
DISCARDFILE 'WRITE_OFF.dsc'
INTO TABLE WRITE_OFF
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    HIST_DATE DATE "YYYY-MM-DD",
    DEAL_NO,
    WRITE_OFF_DATE DATE "YYYY-MM-DD",
    OVERDUE_DATE DATE "YYYY-MM-DD",
    CLIENT_NO,
    CLIENT_SHORT,
    CLIENT_GROUP,
    LOAN_SEGMENT,
    LOAN_PRODUCT,
    SECTOR,
    REGION_BUSINESS,
    BANKER,
    RISK_MANAGER,
    REGIONAL_MANAGER,
    WRITE_OFF_AMOUNT_GEL,
    ALLOWANCE_AT_WRITE_OFF_GEL,
    NET_WRITE_OFF_GEL,
    WRITE_OFF_REASON
)
