OPTIONS (SKIP=1, DIRECT=TRUE, ERRORS=1000)
LOAD DATA
INFILE '../csv/WRO_RECOVERIES.csv'
BADFILE 'WRO_RECOVERIES.bad'
DISCARDFILE 'WRO_RECOVERIES.dsc'
INTO TABLE WRO_RECOVERIES
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    HIST_DATE DATE "YYYY-MM-DD",
    DEAL_NO,
    RECOVERY_AMOUNT_GEL
)
